name: Metrics

on:
  schedule:
    - cron: '0 0 * * *'
    
  workflow_dispatch:
  
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
