name: Profile Assets

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics-assets:
    name: Generate metrics assets
    runs-on: ubuntu-latest

    steps:
      - name: Generate metrics SVG
        uses: gh-metrics/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}

          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large

          output_action: commit
          committer_branch: gh-pages
          committer_message: "ci(profile-assets): update metrics assets"
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_sections: most-used, recently-used

          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          plugin_repositories_pinned: 6

  snake-assets:
    name: Generate snake assets
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Publish snake assets to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: gh-pages
          keep_history: true
          build_dir: dist
          jekyll: false
          commit_message: "ci(profile-assets): update snake assets"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
